version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.7.0
    working_directory: /home/circleci/rosetta
    steps:
      - checkout
      - run: yarn install
      - run: yarn add codecov
      - run: yarn tslint
      - run: yarn type-check
      - run: yarn test
